---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  VCENTER_HOST:
  VCENTER_USR:
  VCENTER_PWD:
  VCENTER_DATA_CENTER:
  NSX_EDGE_GEN_NSX_MANAGER_ADDRESS:
  NSX_EDGE_GEN_NSX_MANAGER_ADMIN_USER:
  NSX_EDGE_GEN_NSX_MANAGER_ADMIN_PASSWD:
  NSX_EDGE_GEN_NSX_MANAGER_TRANSPORT_ZONE:

inputs:
  - name: concourse-vsphere
  - name: nsx-edge-gen

run:
  path: concourse-vsphere/tasks/nsx-edge-gen/task.sh
