---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  VCENTER_HOST:
  VCENTER_USR:
  VCENTER_PWD:
  VCENTER_DATA_CENTER:

inputs:
  - name: concourse-vsphere
  - name: nsx-edge-gen

run:
  path: concourse-vsphere/tasks/nsx-edge-gen/task.sh
